project_id = "ofsyhdnbahjtfxhnuiuv"

[functions.google-places]
verify_jwt = false

[functions.verify-recaptcha]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.sitemap]
verify_jwt = false
